### ISSUE TITLE
Find which fields we need from which components of the Gaia dataset

### ISSUE THREAD

**Issue by KiranEiden** [astro-nerds/stella#1]
For each star we will need coordinates, either a luminosity or an absolute magnitude, and some indicator of color.

[Gaia Documentation](https://gea.esac.esa.int/archive/documentation/index.html)

**Comment by JeffreyMichel** [comment]
Coordinates of a star are given in several forms but I suggest using galactic coordinates, l and b, which can be found in columns 73 and 74 respectively (when brought in using pd.read_csv). There are also several forms for magnitude and luminosity but I suggest phot_g_mean_flux which is the flux received in the G band (673nm in this case) on the vega 0 point scale. I suggest this one because it is the only one with values for all of the stars (column 55). And the color has three options: bp-g, g-rp, bp-rp. I suggest we use one of the first two because we already have the magnitude of g in my list. Unfortunately, colors are not available for all stars. These values are 64 and 65 for the first two and 63 for bp-rp (these are the columns they are found in. bp is 532 nm and rp is 797 nm. Thank you coming to my ted talk
